In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.svm import SVC

In [2]:
df = pd.read_csv('./第六週＋第七週作業/train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

### Q1: 首先，請取出所有的Age跟Sex作為題目，和Survived做為答案並分成三個同名的numpy array。  (10分)
##### (提示： Age.shape = (891, ))

In [3]:
age = np.array(df.Age) 
sex = np.array(df.Sex) 
survived = np.array(df.Survived)
age,sex,survived

(array([ 22.  ,  38.  ,  26.  ,  35.  ,  35.  ,    nan,  54.  ,   2.  ,
         27.  ,  14.  ,   4.  ,  58.  ,  20.  ,  39.  ,  14.  ,  55.  ,
          2.  ,    nan,  31.  ,    nan,  35.  ,  34.  ,  15.  ,  28.  ,
          8.  ,  38.  ,    nan,  19.  ,    nan,    nan,  40.  ,    nan,
           nan,  66.  ,  28.  ,  42.  ,    nan,  21.  ,  18.  ,  14.  ,
         40.  ,  27.  ,    nan,   3.  ,  19.  ,    nan,    nan,    nan,
           nan,  18.  ,   7.  ,  21.  ,  49.  ,  29.  ,  65.  ,    nan,
         21.  ,  28.5 ,   5.  ,  11.  ,  22.  ,  38.  ,  45.  ,   4.  ,
           nan,    nan,  29.  ,  19.  ,  17.  ,  26.  ,  32.  ,  16.  ,
         21.  ,  26.  ,  32.  ,  25.  ,    nan,    nan,   0.83,  30.  ,
         22.  ,  29.  ,    nan,  28.  ,  17.  ,  33.  ,  16.  ,    nan,
         23.  ,  24.  ,  29.  ,  20.  ,  46.  ,  26.  ,  59.  ,    nan,
         71.  ,  23.  ,  34.  ,  34.  ,  28.  ,    nan,  21.  ,  33.  ,
         37.  ,  28.  ,  21.  ,    nan,  38.  ,    nan,  47.  , 

## Q2:其中，由於Age有一些值是空值NaN，請把這些空值都先換成0。   (10分)
#### （提示： 可使用 np.isnan(某個你想確認是不是NaN的年齡) ）

In [4]:
age[(np.isnan(age))] = 0
age

array([ 22.  ,  38.  ,  26.  ,  35.  ,  35.  ,   0.  ,  54.  ,   2.  ,
        27.  ,  14.  ,   4.  ,  58.  ,  20.  ,  39.  ,  14.  ,  55.  ,
         2.  ,   0.  ,  31.  ,   0.  ,  35.  ,  34.  ,  15.  ,  28.  ,
         8.  ,  38.  ,   0.  ,  19.  ,   0.  ,   0.  ,  40.  ,   0.  ,
         0.  ,  66.  ,  28.  ,  42.  ,   0.  ,  21.  ,  18.  ,  14.  ,
        40.  ,  27.  ,   0.  ,   3.  ,  19.  ,   0.  ,   0.  ,   0.  ,
         0.  ,  18.  ,   7.  ,  21.  ,  49.  ,  29.  ,  65.  ,   0.  ,
        21.  ,  28.5 ,   5.  ,  11.  ,  22.  ,  38.  ,  45.  ,   4.  ,
         0.  ,   0.  ,  29.  ,  19.  ,  17.  ,  26.  ,  32.  ,  16.  ,
        21.  ,  26.  ,  32.  ,  25.  ,   0.  ,   0.  ,   0.83,  30.  ,
        22.  ,  29.  ,   0.  ,  28.  ,  17.  ,  33.  ,  16.  ,   0.  ,
        23.  ,  24.  ,  29.  ,  20.  ,  46.  ,  26.  ,  59.  ,   0.  ,
        71.  ,  23.  ,  34.  ,  34.  ,  28.  ,   0.  ,  21.  ,  33.  ,
        37.  ,  28.  ,  21.  ,   0.  ,  38.  ,   0.  ,  47.  ,  14.5 ,
      

### Q3:再來，Sex部分因為都是文字，不方便我們做svm，請把Male都換成0，Female都換成1   （10分）

In [5]:
for i,j in enumerate(sex):
    if (sex[i] == 'male'):
        sex[i] = 0
    elif (sex[i] == 'female'):
        sex[i] = 1
sex

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1,

## Q4:由於我們想把Sex跟Age都當成data，請把Sex和Age兩個array合併成一個。（10分）
## （提示：先用np.reshape，再用np.append）

In [6]:
#age = np.reshape(age,(891,1))
age.shape = (891,1)
sex = np.reshape(sex,(891,1))
age,sex
#sexPlusAge = np.column_stack((sex,age))
sexPlusAge = np.c_[sex,age]
sexPlusAge

array([[0, 22.0],
       [1, 38.0],
       [1, 26.0],
       ..., 
       [1, 0.0],
       [0, 26.0],
       [0, 32.0]], dtype=object)

## Q5: 實際拿svm 訓練看看，並用同樣的data，preict看看結果（這次不用分training data跟testing data）
#### （這次是因為前面做過了，一般都還是要噢！）(10分)

In [7]:
clf = SVC()

In [8]:
survived = np.reshape(survived,(891,-1))
x = sexPlusAge
y = survived
x,y

(array([[0, 22.0],
        [1, 38.0],
        [1, 26.0],
        ..., 
        [1, 0.0],
        [0, 26.0],
        [0, 32.0]], dtype=object), array([[0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],


In [9]:
clf.fit(x,y)

/home/jokefish/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
clf.predict([[0,30]]),clf.predict([[1,32]]),clf.predict([[0,74]])

(array([0]), array([1]), array([0]))

In [11]:
clf.predict(x)

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1,

In [12]:
clf.score(x,y) #平均預測正確率(Returns the mean accuracy on the given test data and labels) 

0.80808080808080807

## Q.6 加分題： 請設計一種方法，比較看看你的預測結果，和正確答案(Survived)，
## 找出你的「預測正確率」是多少。 (10分)

### Ans:取出所有的Age跟Fare作為題目，和Survived做為答案並分成三個同名的numpy array

In [13]:
age = np.array(df.Age) 
fare = np.array(df.Fare) 
survived = np.array(df.Survived)
age[(np.isnan(age))] = 0
age,fare,survived

(array([ 22.  ,  38.  ,  26.  ,  35.  ,  35.  ,   0.  ,  54.  ,   2.  ,
         27.  ,  14.  ,   4.  ,  58.  ,  20.  ,  39.  ,  14.  ,  55.  ,
          2.  ,   0.  ,  31.  ,   0.  ,  35.  ,  34.  ,  15.  ,  28.  ,
          8.  ,  38.  ,   0.  ,  19.  ,   0.  ,   0.  ,  40.  ,   0.  ,
          0.  ,  66.  ,  28.  ,  42.  ,   0.  ,  21.  ,  18.  ,  14.  ,
         40.  ,  27.  ,   0.  ,   3.  ,  19.  ,   0.  ,   0.  ,   0.  ,
          0.  ,  18.  ,   7.  ,  21.  ,  49.  ,  29.  ,  65.  ,   0.  ,
         21.  ,  28.5 ,   5.  ,  11.  ,  22.  ,  38.  ,  45.  ,   4.  ,
          0.  ,   0.  ,  29.  ,  19.  ,  17.  ,  26.  ,  32.  ,  16.  ,
         21.  ,  26.  ,  32.  ,  25.  ,   0.  ,   0.  ,   0.83,  30.  ,
         22.  ,  29.  ,   0.  ,  28.  ,  17.  ,  33.  ,  16.  ,   0.  ,
         23.  ,  24.  ,  29.  ,  20.  ,  46.  ,  26.  ,  59.  ,   0.  ,
         71.  ,  23.  ,  34.  ,  34.  ,  28.  ,   0.  ,  21.  ,  33.  ,
         37.  ,  28.  ,  21.  ,   0.  ,  38.  ,   0.  ,  47.  , 

In [14]:
age.shape = (891,1)
fare = np.reshape(fare,(891,1))
age,fare
farePlusAge = np.c_[fare,age]
farePlusAge

array([[  7.25  ,  22.    ],
       [ 71.2833,  38.    ],
       [  7.925 ,  26.    ],
       ..., 
       [ 23.45  ,   0.    ],
       [ 30.    ,  26.    ],
       [  7.75  ,  32.    ]])

In [15]:
clf2 = SVC()

In [16]:
survived = np.reshape(survived,(891,-1))
x = farePlusAge
y = survived
x,y

(array([[  7.25  ,  22.    ],
        [ 71.2833,  38.    ],
        [  7.925 ,  26.    ],
        ..., 
        [ 23.45  ,   0.    ],
        [ 30.    ,  26.    ],
        [  7.75  ,  32.    ]]), array([[0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [0],
        [1],

In [17]:
clf2.fit(x,y)

/home/jokefish/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [18]:
clf2.predict([[9,30]]),clf.predict([[2,32]]),clf.predict([[100,74]])

(array([0]), array([1]), array([0]))

In [19]:
clf2.predict(x)

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0,

In [20]:
clf2.score(x,y)

0.87317620650953987

## 把題目X，答案Y再分成佔80%的訓練資料跟佔20%的測試資料

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=99)
len(x_train),len(x_test),len(y_train),len(y_test)

(712, 179, 712, 179)

In [23]:
x_train = x_train.reshape(712,-1)
x_test.shape = (179,-1)
x_train,x_test

(array([[ 39.6875,  16.    ],
        [ 26.    ,  54.    ],
        [ 13.5   ,  45.    ],
        ..., 
        [ 50.    ,   0.    ],
        [ 52.    ,  42.    ],
        [ 69.3   ,  24.    ]]), array([[  14.5   ,   24.    ],
        [  12.475 ,   27.    ],
        [   7.8958,   19.    ],
        [  13.    ,   25.    ],
        [  13.    ,   24.    ],
        [  46.9   ,    9.    ],
        [  34.375 ,   16.    ],
        [  26.2833,   19.    ],
        [  16.1   ,   30.    ],
        [  53.1   ,   33.    ],
        [   7.75  ,   16.    ],
        [  26.    ,   27.    ],
        [  29.    ,    0.83  ],
        [   6.75  ,   18.    ],
        [  21.6792,    0.    ],
        [  53.1   ,   35.    ],
        [  89.1042,   49.    ],
        [  10.5   ,   17.    ],
        [   7.4958,   24.    ],
        [   0.    ,    0.    ],
        [   6.2375,   61.    ],
        [   7.75  ,   21.    ],
        [  39.6875,    7.    ],
        [  13.    ,   25.    ],
        [  31.275 ,    6.    ],
     

In [24]:
regr = LinearRegression()
regr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
clf2.fit(x_train,y_train)

/home/jokefish/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
clf2.predict([[3,30]]),clf.predict([[2,32]]),clf.predict([[88,74]])

(array([0]), array([1]), array([0]))

In [27]:
clf2.fit(x_test,y_test)

/home/jokefish/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
clf2.predict([[3,30]]),clf.predict([[2,32]]),clf.predict([[88,74]])

(array([0]), array([1]), array([0]))

In [29]:
clf2.score(x_train,y_train),clf.score(x_test,y_test)  #平均預測正確率(Returns the mean accuracy)

(0.6179775280898876, 0.63128491620111726)