In [5]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [24]:
A = np.random.random(100)

In [25]:
A

array([ 0.91420564,  0.95116484,  0.15249325,  0.11198937,  0.21232186,
        0.12798345,  0.03790679,  0.87726493,  0.94348351,  0.34518383,
        0.98074555,  0.43756833,  0.37910909,  0.75690122,  0.67584972,
        0.38406364,  0.5537884 ,  0.10549211,  0.01446507,  0.70195483,
        0.913526  ,  0.20375021,  0.12663516,  0.34938433,  0.7222191 ,
        0.06149525,  0.76002442,  0.26734269,  0.21976286,  0.48134484,
        0.40371128,  0.40434292,  0.83415884,  0.05482221,  0.09102111,
        0.15480336,  0.65896214,  0.85408303,  0.58635095,  0.41839705,
        0.7912115 ,  0.39829283,  0.76588571,  0.65476554,  0.93136518,
        0.48315518,  0.10085456,  0.78098692,  0.68354521,  0.3278854 ,
        0.45609787,  0.30724153,  0.92313921,  0.28717296,  0.41189511,
        0.55732259,  0.98773066,  0.93627153,  0.2375513 ,  0.2255369 ,
        0.88727153,  0.89549656,  0.03715891,  0.18061667,  0.29147349,
        0.50322322,  0.21750721,  0.2349123 ,  0.50658131,  0.32

In [26]:
A = 10*A 

In [21]:
A

array([ 57793.9840753 ,  51482.58483364,  58689.21900206,  57295.28427541,
        54143.72321787,  50709.00594325,  54836.15345975,  51712.29600013,
        54202.53965082,  57792.27159351,  53906.5353625 ,  59168.36256018,
        58836.2856125 ,  54532.30190433,  55086.253302  ,  53634.03828467,
        50289.43253722,  57868.60336102,  56608.83722677,  58858.22672547,
        57902.38144982,  57815.24666578,  52807.7297222 ,  50592.58289887,
        57075.35596362,  54285.88033312,  57246.56033417,  53727.93502597,
        58414.23921454,  55155.05604185,  52574.74425876,  54180.45765536,
        58816.38993927,  51521.09240267,  54857.83065104,  58108.94575756,
        54467.44194638,  57019.95030928,  54662.28837549,  51268.52240396,
        50693.2477292 ,  51061.63370424,  51449.19268374,  54864.5364322 ,
        53704.15897874,  59724.11897729,  50160.94807899,  56040.94375434,
        52369.44256676,  55110.59691355,  57273.83361161,  50578.22107707,
        57799.31286824,  

變成5*20的向量

In [6]:
A.shape = (5,20)

In [7]:
Ａ

array([[ 43.08883811,  55.9702219 ,  44.98054262,  60.57549342,
         46.78405778,  55.02830782,  38.37948755,  40.3549171 ,
         52.6987678 ,  47.63681542,  41.52646201,  49.90530782,
         51.30823644,  53.64866509,  64.26959117,  48.41720404,
         55.47532235,  54.49145014,  65.8670573 ,  44.71351432],
       [ 61.47707342,  56.15996989,  48.01131189,  74.92401146,
         21.74672587,  42.96391716,  59.50208675,  61.4888704 ,
         43.82851471,  65.30300869,  54.0196833 ,  49.51175955,
         54.68053039,  38.54685303,  37.81397736,  45.42301876,
         45.82595289,  44.86829068,  41.26883745,  31.13060463],
       [ 55.26753243,  48.02517896,  63.61791147,  49.89409227,
         47.50702503,  73.70990989,  48.35439708,  55.7391728 ,
         49.56894645,  47.62914103,  47.05236923,  53.52429256,
         48.31479723,  49.91839621,  40.73340123,  52.94096117,
         45.56401785,  44.75612348,  49.57282009,  57.02182205],
       [ 43.3492695 ,  57.00591899,  

另一種變法

In [9]:
A.reshape(100,1)

array([[ 43.08883811],
       [ 55.9702219 ],
       [ 44.98054262],
       [ 60.57549342],
       [ 46.78405778],
       [ 55.02830782],
       [ 38.37948755],
       [ 40.3549171 ],
       [ 52.6987678 ],
       [ 47.63681542],
       [ 41.52646201],
       [ 49.90530782],
       [ 51.30823644],
       [ 53.64866509],
       [ 64.26959117],
       [ 48.41720404],
       [ 55.47532235],
       [ 54.49145014],
       [ 65.8670573 ],
       [ 44.71351432],
       [ 61.47707342],
       [ 56.15996989],
       [ 48.01131189],
       [ 74.92401146],
       [ 21.74672587],
       [ 42.96391716],
       [ 59.50208675],
       [ 61.4888704 ],
       [ 43.82851471],
       [ 65.30300869],
       [ 54.0196833 ],
       [ 49.51175955],
       [ 54.68053039],
       [ 38.54685303],
       [ 37.81397736],
       [ 45.42301876],
       [ 45.82595289],
       [ 44.86829068],
       [ 41.26883745],
       [ 31.13060463],
       [ 55.26753243],
       [ 48.02517896],
       [ 63.61791147],
       [ 49

In [10]:
A

array([[ 43.08883811,  55.9702219 ,  44.98054262,  60.57549342,
         46.78405778,  55.02830782,  38.37948755,  40.3549171 ,
         52.6987678 ,  47.63681542,  41.52646201,  49.90530782,
         51.30823644,  53.64866509,  64.26959117,  48.41720404,
         55.47532235,  54.49145014,  65.8670573 ,  44.71351432],
       [ 61.47707342,  56.15996989,  48.01131189,  74.92401146,
         21.74672587,  42.96391716,  59.50208675,  61.4888704 ,
         43.82851471,  65.30300869,  54.0196833 ,  49.51175955,
         54.68053039,  38.54685303,  37.81397736,  45.42301876,
         45.82595289,  44.86829068,  41.26883745,  31.13060463],
       [ 55.26753243,  48.02517896,  63.61791147,  49.89409227,
         47.50702503,  73.70990989,  48.35439708,  55.7391728 ,
         49.56894645,  47.62914103,  47.05236923,  53.52429256,
         48.31479723,  49.91839621,  40.73340123,  52.94096117,
         45.56401785,  44.75612348,  49.57282009,  57.02182205],
       [ 43.3492695 ,  57.00591899,  

reshape是產生新的array，不會改變本身
要變得話，就要用A=A.reshape

In [11]:
A = A.reshape(100,1)

In [12]:
Ａ

array([[ 43.08883811],
       [ 55.9702219 ],
       [ 44.98054262],
       [ 60.57549342],
       [ 46.78405778],
       [ 55.02830782],
       [ 38.37948755],
       [ 40.3549171 ],
       [ 52.6987678 ],
       [ 47.63681542],
       [ 41.52646201],
       [ 49.90530782],
       [ 51.30823644],
       [ 53.64866509],
       [ 64.26959117],
       [ 48.41720404],
       [ 55.47532235],
       [ 54.49145014],
       [ 65.8670573 ],
       [ 44.71351432],
       [ 61.47707342],
       [ 56.15996989],
       [ 48.01131189],
       [ 74.92401146],
       [ 21.74672587],
       [ 42.96391716],
       [ 59.50208675],
       [ 61.4888704 ],
       [ 43.82851471],
       [ 65.30300869],
       [ 54.0196833 ],
       [ 49.51175955],
       [ 54.68053039],
       [ 38.54685303],
       [ 37.81397736],
       [ 45.42301876],
       [ 45.82595289],
       [ 44.86829068],
       [ 41.26883745],
       [ 31.13060463],
       [ 55.26753243],
       [ 48.02517896],
       [ 63.61791147],
       [ 49