In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

# 第二題

In [11]:
a = np.random.randint(1,100,150)
grades = a.reshape(3,10,5)
weights = np.array([0.25,0.25,0.25,0.15,0.10])
b = np.dot(grades,weights)
cl = np.dot(b,[0.1]*10)
print ("全校成績"+","+ str(grades)+"個人加權平均"+str(b))
for i in range(3):
    a = b[i]
    c = (b[i].sum())/10
    i = i+1
    print("第"+str(i)+"班個人加權成績："+ str(a),"","全班加權平均成績："+ str(c))

全校成績,[[[44 74 58 93 92]
  [ 8 49 62 34 53]
  [96 10  2 23 42]
  [98 40 89 52 74]
  [41 18 87 29 49]
  [23 53  2 85 48]
  [82 18 70 19 52]
  [29 37 39 21 29]
  [88 46 58 79 97]
  [41 69  6 43 32]]

 [[81 65 54 62  2]
  [79  8 18 43 51]
  [38 87 66 45 89]
  [73 81 71 20 61]
  [10 90 50 82 69]
  [94 20 18 62 36]
  [58 88 66 22 45]
  [82 36 18 72 93]
  [47 87 79 97  8]
  [82 32 33 12 52]]

 [[55  1 83 62 70]
  [42 33 48 41 17]
  [82  5 45  1 80]
  [26 58 26 37 54]
  [37 48 60 65 20]
  [18 52 32 92 74]
  [80 43 84  2 16]
  [90 40 90  7 10]
  [36 53 23 60 37]
  [27 69 45 16 27]]]個人加權平均[[ 67.15  40.15  34.65  71.95  45.75  37.05  50.55  32.3   69.55  38.65]
 [ 59.5   37.8   63.4   65.35  56.7   45.9   60.8   54.1   68.6   43.75]
 [ 51.05  38.6   41.15  38.45  48.    46.7   53.65  57.05  40.7   40.35]]
第1班個人加權成績：[ 67.15  40.15  34.65  71.95  45.75  37.05  50.55  32.3   69.55  38.65]  全班加權平均成績：48.775
第2班個人加權成績：[ 59.5   37.8   63.4   65.35  56.7   45.9   60.8   54.1   68.6   43.75]  全班加權平均成績：55.

In [12]:
cl

array([ 48.775,  55.59 ,  45.57 ])

為何0.1＊10就可以變成三個！？！？