# 第二題

## 請算出A, B, C班級，每個學生的加權平均成績。

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A = np.random.randint(1, 100, 150)

In [3]:
A

array([26, 33, 86, 48,  1, 20, 15, 86, 53, 39, 27, 72, 96, 20, 90, 10,  5,
       49, 78, 28, 91, 65, 65, 94, 43, 37, 48, 31, 74,  9, 88, 88, 36, 70,
       23, 63, 79, 53, 45, 27, 34, 11, 42,  7, 52, 93, 26, 29, 77, 74, 92,
       23, 44, 39, 23, 74, 91, 54, 24, 23, 57, 45, 21, 72, 11, 62, 91, 82,
       78,  6, 91, 31, 64, 99, 71, 12, 10, 70, 30, 99,  4, 71, 92,  6,  9,
       73, 58,  1, 35, 90, 36, 50, 28, 67, 69, 82,  6,  9, 63, 21, 71, 77,
       30, 99, 69, 99, 47, 28, 51, 57, 74, 49, 28, 84, 41, 32, 76, 95, 40,
       18, 37, 81, 41, 12, 21, 31, 43, 49, 91, 69, 53, 88, 37, 21, 43, 53,
       53, 20, 23, 89, 66, 45,  4, 23, 29, 28, 11,  1, 48,  9])

In [4]:
A.shape =(3, 10, 5)

In [5]:
A

array([[[26, 33, 86, 48,  1],
        [20, 15, 86, 53, 39],
        [27, 72, 96, 20, 90],
        [10,  5, 49, 78, 28],
        [91, 65, 65, 94, 43],
        [37, 48, 31, 74,  9],
        [88, 88, 36, 70, 23],
        [63, 79, 53, 45, 27],
        [34, 11, 42,  7, 52],
        [93, 26, 29, 77, 74]],

       [[92, 23, 44, 39, 23],
        [74, 91, 54, 24, 23],
        [57, 45, 21, 72, 11],
        [62, 91, 82, 78,  6],
        [91, 31, 64, 99, 71],
        [12, 10, 70, 30, 99],
        [ 4, 71, 92,  6,  9],
        [73, 58,  1, 35, 90],
        [36, 50, 28, 67, 69],
        [82,  6,  9, 63, 21]],

       [[71, 77, 30, 99, 69],
        [99, 47, 28, 51, 57],
        [74, 49, 28, 84, 41],
        [32, 76, 95, 40, 18],
        [37, 81, 41, 12, 21],
        [31, 43, 49, 91, 69],
        [53, 88, 37, 21, 43],
        [53, 53, 20, 23, 89],
        [66, 45,  4, 23, 29],
        [28, 11,  1, 48,  9]]])

In [6]:
weights = np.array([0.25, 0.25, 0.25, 0.15, 0.1])

In [7]:
np.dot(A, weights)

array([[ 43.55,  42.1 ,  60.75,  30.5 ,  73.65,  41.  ,  65.8 ,  58.2 ,
         28.  ,  55.95],
       [ 47.9 ,  60.65,  42.65,  71.05,  68.45,  37.4 ,  43.55,  47.25,
         45.45,  35.8 ],
       [ 66.25,  56.85,  54.45,  58.55,  43.65,  51.3 ,  51.95,  43.85,
         35.1 ,  18.1 ]])

## 額外自己做的作業， 以班級為單位算出平均加權值

In [7]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [9]:
A = np.random.randint(1, 100, 150)

In [12]:
A.shape =(3, 10, 5)

In [13]:
A

array([[[54, 91, 83, 31, 50],
        [65, 36, 66, 99, 53],
        [35, 83, 58, 47, 46],
        [89, 63, 49, 65, 14],
        [22, 99, 62, 47,  1],
        [ 4, 35, 12, 36, 25],
        [71, 34, 30, 21, 74],
        [53, 73, 68, 98, 73],
        [20, 85, 65, 56, 70],
        [49, 87, 74, 11, 56]],

       [[52, 79, 98, 49, 12],
        [75, 55, 17, 86,  9],
        [ 6, 83, 27, 60, 69],
        [42, 32, 24, 16, 30],
        [15, 27, 31, 91, 64],
        [22, 47, 66, 82, 91],
        [46, 57, 31, 59, 87],
        [79, 88, 28, 23, 99],
        [13, 31, 14, 82, 46],
        [54, 76, 31, 70, 35]],

       [[58, 51, 61, 63, 90],
        [16, 62, 49, 74, 68],
        [60, 49, 49, 68, 85],
        [34, 39, 92, 69, 59],
        [13, 65, 66, 79, 86],
        [96, 65, 36, 26, 93],
        [65, 39, 30, 32, 32],
        [51, 98, 64, 74, 24],
        [63, 86, 75,  2, 98],
        [24, 13, 78, 99, 51]]])

In [18]:
weights = np.array([0.25, 0.25, 0.25, 0.15, 0.1])

In [20]:
Class1 = np.dot(A[0:10:30], weights)
print(np.mean(Class1))

55.16


In [21]:
Class2 = np.dot(A[1:10:30], weights)
print(np.mean(Class2))

48.34


In [22]:
Class3 = np.dot(A[2:10:30], weights)
print(np.mean(Class3))

56.825


### 只是自己做紀錄哦~ 