In [6]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 第一題

In [7]:
def 閏年 (Y):
    if Y%4==0 or (Y%100 == 0 and Y%400 != 0):
        print(str(Y)+" 不是閏年")
    else:
        print(str(Y)+" 是閏年")

In [8]:
閏年(1994)

1994 是閏年


# 第二題

In [9]:
A1= np.random.rand(5,5)

In [10]:
A1

array([[ 0.93870503,  0.12187589,  0.42705056,  0.456039  ,  0.63643077],
       [ 0.67582216,  0.77567329,  0.12147373,  0.50577585,  0.96254171],
       [ 0.8138508 ,  0.54371779,  0.37421428,  0.22134979,  0.1915351 ],
       [ 0.02272426,  0.54592377,  0.18132777,  0.17915461,  0.86495107],
       [ 0.07013346,  0.75359628,  0.01574792,  0.04109635,  0.08472219]])

In [11]:
A2= np.random.rand(5,5)

In [12]:
A2

array([[ 0.47000924,  0.68787504,  0.02870643,  0.80744433,  0.19972405],
       [ 0.34758583,  0.36785828,  0.37414066,  0.26306264,  0.87963888],
       [ 0.48915853,  0.15029588,  0.26038466,  0.03701658,  0.54284952],
       [ 0.2356298 ,  0.20045836,  0.77794537,  0.3851025 ,  0.90567794],
       [ 0.40491052,  0.11590564,  0.51946141,  0.11570806,  0.14945467]])

In [13]:
A=A1+A2

In [14]:
def A(A1, A2):
    A= np.matrix(A1) + np.matrix(A2)
    return A

In [15]:
A(A1,A2)

matrix([[ 1.40871428,  0.80975093,  0.455757  ,  1.26348333,  0.83615482],
        [ 1.02340798,  1.14353157,  0.49561439,  0.7688385 ,  1.84218059],
        [ 1.30300933,  0.69401367,  0.63459894,  0.25836637,  0.73438462],
        [ 0.25835406,  0.74638213,  0.95927314,  0.56425712,  1.77062901],
        [ 0.47504398,  0.86950192,  0.53520934,  0.15680441,  0.23417686]])